## Agregación de datos por categoría

In [1]:
import numpy as np
import pandas as pd

In [2]:
gender = ["Male", "Female"]
income = ["Poor", "Middle Class", "Rich"]

In [3]:
n = 500
gender_data = []
income_data = []

for i in range(0, 500): 
    #Para elegir data aleatoria de gender(array)
    gender_data.append(np.random.choice(gender))
    income_data.append(np.random.choice(income))

In [5]:
gender_data

['Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female']

In [6]:
#N(m, s) -> m(media) + s(desviacion tipíca) * Z (normal)
height = 160 + 30 * np.random.randn(n)
weight = 65 + 25 * np.random.randn(n)
age = 30 + 12 * np.random.randn(n)
income  = 18000 + 3500 * np.random.randn(n)

In [7]:
data = pd.DataFrame(
    {
        'Gender': gender_data,
        "Economic Status": income_data,
        'Height': height,
        'Weight': weight,
        'Age': age,
        'Income': income
    }
)

In [8]:
data.head()

   Gender Economic Status      Height      Weight        Age        Income
0  Female            Poor  145.003227  104.034597  35.487417  22581.327698
1  Female            Rich  180.604114  117.536593  34.434287  16329.305814
2    Male    Middle Class  147.554611  104.795530  28.570812  17688.434184
3    Male            Poor  164.818786   75.742774  52.777811  18062.585082
4  Female            Rich  159.208301   69.259598   2.719651  14976.682980

## Agrupacion de datos

In [10]:
grouped_gender = data.groupby("Gender")

In [13]:
grouped_gender.groups

{'Female': Int64Index([  0,   1,   4,   5,   7,  10,  13,  18,  19,  21,
             ...
             465, 469, 475, 476, 481, 484, 487, 488, 497, 499],
            dtype='int64', length=232),
 'Male': Int64Index([  2,   3,   6,   8,   9,  11,  12,  14,  15,  16,
             ...
             486, 489, 490, 491, 492, 493, 494, 495, 496, 498],
            dtype='int64', length=268)}

In [15]:
for name, groups in grouped_gender:
    print(name)
    print(groups)

Female
     Gender Economic Status      Height      Weight        Age        Income
0    Female            Poor  145.003227  104.034597  35.487417  22581.327698
1    Female            Rich  180.604114  117.536593  34.434287  16329.305814
4    Female            Rich  159.208301   69.259598   2.719651  14976.682980
5    Female            Poor  169.343943   62.796247  36.268538  27980.733982
7    Female            Rich  164.237406   78.326334  23.116249  22244.870079
10   Female    Middle Class   99.326653   35.177586  33.386594  21926.707857
13   Female            Rich  152.293354   93.731695  45.951931  10386.486258
18   Female            Rich  166.928437   50.933272  35.030621  14098.546877
19   Female    Middle Class  163.119879   40.548448  29.989267  20772.916430
21   Female    Middle Class  192.927230   45.182203  50.816121  15472.304732
24   Female            Rich  119.678582   58.975352   8.585459  11921.018746
25   Female            Rich  123.159493   27.463171  36.441056  14149.203225
28   Female    Middle Class  161.033834   89.345970  19.447700  21367.110214
29   Female            Poor  107.042841   54.757581  23.665133  18302.670076
30   Female            Rich  133.286488   61.883725  26.536875  21579.732351
34   Female            Poor  174.173457   48.564740  21.621477  12041.856169
35   Female            Poor  181.898603   34.973609  13.394481  21922.464712
39   Female    Middle Class  129.021196   75.872575  36.757063  11470.084742
41   Female            Rich  200.861964   39.735186  27.306176  19439.231158
42   Female            Poor  169.982715   73.724865  31.504943  15561.156633
46   Female            Poor  135.724487  110.743670  32.651952  19647.050491
47   Female            Rich  156.172039   62.424292  27.355375  17730.114720
48   Female            Poor  106.943685   89.229003  39.220421  16544.362150
50   Female    Middle Class  183.357699   70.987025  14.985370  23436.614682
54   Female            Poor  178.668405   93.795211  21.025664  20773.193130
56   Female    Middle Class  100.694266   63.374240  36.788290  28322.393609
58   Female            Rich  149.749473   61.038524  34.386311  18273.116454
59   Female            Rich  141.634627   49.627084  29.078225  12845.165867
60   Female            Rich  142.299955   82.230375  29.664663  16936.246523
61   Female            Poor  153.286507   76.487103  53.117450  16626.242088
..      ...             ...         ...         ...        ...           ...
430  Female            Rich  204.077483   73.924711  13.181464  18586.719943
432  Female    Middle Class  170.275384   48.834834  47.378284  16257.070250
434  Female    Middle Class  205.721833   46.089356  28.127938  20573.801101
435  Female            Rich  201.695130   47.953294  12.164638  21319.987698
437  Female            Rich  141.463187   81.432313  41.165810  22993.657991
440  Female            Poor  181.175932   96.729312  24.682871  20988.601022
441  Female            Poor  180.761383   43.873204  28.237756  20218.364184
443  Female            Poor  191.956861   59.530944  24.467168  19823.324263
444  Female    Middle Class  158.088381   66.271985  35.417270  23573.618081
446  Female    Middle Class  137.635809   84.574914  15.826346  15403.117296
447  Female    Middle Class  173.446510   93.515137  43.908351  17833.371375
448  Female    Middle Class  142.314597   51.842130  29.871398  18028.243907
449  Female            Poor  198.232184   52.942944  36.373628  16816.901389
450  Female    Middle Class  110.840841   58.122349  20.412186  15921.757539
451  Female            Rich  180.235406   78.990422  26.241729   8841.596690
456  Female            Rich  174.619964   79.549642  22.994649  12215.187011
457  Female            Rich  143.550091   45.388712  35.221450  16908.264982
460  Female            Rich  155.167588    2.963596  26.969665  19197.000268
461  Female    Middle Class  204.619591   53.444895  44.380174  15955.391015
463  Female            Poor  188.178427   33.644124  26.556408  18364.244058
465  Female            Poor  142.781643   83.141827  22.396599  21410.198725
469  Female            Rich  166.311096   24.896342  33.107142  18720.850812
475  Female            Rich  177.219196   82.332669  29.908853  18329.087880
476  Female            Rich  171.989711   54.983507  12.447203  19783.184568
481  Female            Rich  160.100761   98.372355  45.858553  12788.860484
484  Female            Poor  147.170746  100.789389  45.432393  20199.561595
487  Female            Poor  150.379291   88.991787  17.749186  15833.347376
488  Female            Rich  189.925318   60.232040  28.158365  17666.024486
497  Female    Middle Class  130.093762   69.843849  13.326383  16948.866528
499  Female            Poor  153.154213   67.495291  25.662428  22223.983510

[232 rows x 6 columns]
Male
    Gender Economic Status      Height      Weight        Age        Income
2     Male    Middle Class  147.554611  104.795530  28.570812  17688.434184
3     Male            Poor  164.818786   75.742774  52.777811  18062.585082
6     Male            Poor  149.074546   72.288429  18.346359  19159.739373
8     Male            Poor  164.405278   55.250224  19.038873  28492.025708
9     Male            Poor  194.896210   47.093524  43.412001  19241.182225
11    Male    Middle Class  184.342331   48.014228  23.479574  14414.868112
12    Male    Middle Class  204.313096   81.602032  29.893581  19789.049595
14    Male    Middle Class  140.475187   51.435623  22.462881  17778.968241
15    Male    Middle Class  161.318227  100.840180  32.648121  17058.469525
16    Male            Poor  121.271774   22.903726  38.527925  20562.214179
17    Male            Rich  139.632577   77.044936  10.105936  24339.736329
20    Male            Poor  204.025779   72.348873  25.454164  22060.505237
22    Male            Rich  194.048094   67.484881  46.353745  14025.804573
23    Male            Poor  168.698690   15.276777  21.529697  22121.246982
26    Male            Poor  152.781105   57.876538  21.590702  20747.105554
27    Male    Middle Class  196.679721   46.576822  24.765471  18049.892282
31    Male            Poor  203.015010   68.669956  20.893979  16636.380866
32    Male    Middle Class  165.914861   92.906733  42.620675  13951.012223
33    Male            Rich  181.486585   68.811543  15.986836  16996.841187
36    Male    Middle Class  195.961298   54.031312  29.771976  16400.552096
37    Male            Rich  165.060299   62.742216  19.426093  19638.453394
38    Male    Middle Class  141.754044   67.222383  39.076269  25803.844847
40    Male            Rich  157.694687   74.591607  16.393456  13584.769698
43    Male            Rich  124.948835   60.515498  27.189512  18102.511066
44    Male            Poor  134.802127   56.513904  26.785885  18839.547356
45    Male            Poor  148.737419   14.144696  41.673333  18677.548694
49    Male            Rich  129.110390   69.696048  48.582695  24733.317302
51    Male    Middle Class  157.042143   92.499571  37.315108  19439.465111
52    Male            Poor  132.776988   49.284208  26.520021  21271.097165
53    Male    Middle Class  170.093600   90.078229  36.445166  16491.651714
..     ...             ...         ...         ...        ...           ...
455   Male            Rich  190.116039   -0.794429  30.628564  11707.667103
458   Male            Rich  203.168543   50.628997  28.678238  17304.692695
459   Male    Middle Class  169.983493   80.378619  21.936908  11159.016363
462   Male            Rich  170.244861   81.710770  48.704025  18083.354343
464   Male    Middle Class  182.205639   34.025972  34.727108  21347.384731
466   Male    Middle Class  134.760997   50.674127  24.641276  15648.641449
467   Male            Poor  249.149445   83.698674  13.781408  14822.630953
468   Male            Poor  195.732772   81.335653  19.578940  24469.049430
470   Male            Rich  177.642008  102.256793  50.064074  23162.302333
471   Male            Poor  152.753535   34.463207  11.387913  22074.350845
472   Male    Middle Class  222.407230   43.497227  52.776090  15069.842875
473   Male    Middle Class  144.038160   69.724514  22.190778  15550.606666
474   Male            Rich  171.483638   34.914549  29.244635  17180.236299
477   Male            Rich  158.464813   51.485825  47.407893  10877.780656
478   Male            Rich  149.691377   50.618778  26.031569  16152.327953
479   Male            Poor  158.113754   58.215624  44.964595  15068.458263
480   Male    Middle Class  172.008682  127.911154  33.317179  19265.960131
482   Male    Middle Class  192.663626   80.253718  35.049361  21342.630833
483   Male            Poor  161.473927   78.190176  42.409741  15350.543302
485   Male            Poor  164.586586   71.269192  32.509345  22653.589403
486   Male            Rich  192.646453   69.884509  22.283310  18334.349858
489   Male            Poor  160.020285   59.445757  26.930313  23782.626247
490   Male    Middle Class  142.540566   90.182336  33.021074  20601.926604
491   Male    Middle Class  155.922252   82.555797  59.793334  19042.724663
492   Male    Middle Class  175.056187   39.526115  26.904006  19975.560946
493   Male            Rich  249.863699   88.308869  31.344662  14994.542684
494   Male            Poor  163.469316   63.346755  36.050647  18733.594140
495   Male    Middle Class  110.566745   46.193122  30.404502  14801.618029
496   Male            Poor  235.266066  111.322790  34.971332  12726.785905
498   Male            Poor  126.347920  108.458229  21.389828  17120.892004

[268 rows x 6 columns]

In [16]:
grouped_gender.get_group('Female')

     Gender Economic Status      Height      Weight        Age        Income
0    Female            Poor  145.003227  104.034597  35.487417  22581.327698
1    Female            Rich  180.604114  117.536593  34.434287  16329.305814
4    Female            Rich  159.208301   69.259598   2.719651  14976.682980
5    Female            Poor  169.343943   62.796247  36.268538  27980.733982
7    Female            Rich  164.237406   78.326334  23.116249  22244.870079
10   Female    Middle Class   99.326653   35.177586  33.386594  21926.707857
13   Female            Rich  152.293354   93.731695  45.951931  10386.486258
18   Female            Rich  166.928437   50.933272  35.030621  14098.546877
19   Female    Middle Class  163.119879   40.548448  29.989267  20772.916430
21   Female    Middle Class  192.927230   45.182203  50.816121  15472.304732
24   Female            Rich  119.678582   58.975352   8.585459  11921.018746
25   Female            Rich  123.159493   27.463171  36.441056  14149.203225
28   Female    Middle Class  161.033834   89.345970  19.447700  21367.110214
29   Female            Poor  107.042841   54.757581  23.665133  18302.670076
30   Female            Rich  133.286488   61.883725  26.536875  21579.732351
34   Female            Poor  174.173457   48.564740  21.621477  12041.856169
35   Female            Poor  181.898603   34.973609  13.394481  21922.464712
39   Female    Middle Class  129.021196   75.872575  36.757063  11470.084742
41   Female            Rich  200.861964   39.735186  27.306176  19439.231158
42   Female            Poor  169.982715   73.724865  31.504943  15561.156633
46   Female            Poor  135.724487  110.743670  32.651952  19647.050491
47   Female            Rich  156.172039   62.424292  27.355375  17730.114720
48   Female            Poor  106.943685   89.229003  39.220421  16544.362150
50   Female    Middle Class  183.357699   70.987025  14.985370  23436.614682
54   Female            Poor  178.668405   93.795211  21.025664  20773.193130
56   Female    Middle Class  100.694266   63.374240  36.788290  28322.393609
58   Female            Rich  149.749473   61.038524  34.386311  18273.116454
59   Female            Rich  141.634627   49.627084  29.078225  12845.165867
60   Female            Rich  142.299955   82.230375  29.664663  16936.246523
61   Female            Poor  153.286507   76.487103  53.117450  16626.242088
..      ...             ...         ...         ...        ...           ...
430  Female            Rich  204.077483   73.924711  13.181464  18586.719943
432  Female    Middle Class  170.275384   48.834834  47.378284  16257.070250
434  Female    Middle Class  205.721833   46.089356  28.127938  20573.801101
435  Female            Rich  201.695130   47.953294  12.164638  21319.987698
437  Female            Rich  141.463187   81.432313  41.165810  22993.657991
440  Female            Poor  181.175932   96.729312  24.682871  20988.601022
441  Female            Poor  180.761383   43.873204  28.237756  20218.364184
443  Female            Poor  191.956861   59.530944  24.467168  19823.324263
444  Female    Middle Class  158.088381   66.271985  35.417270  23573.618081
446  Female    Middle Class  137.635809   84.574914  15.826346  15403.117296
447  Female    Middle Class  173.446510   93.515137  43.908351  17833.371375
448  Female    Middle Class  142.314597   51.842130  29.871398  18028.243907
449  Female            Poor  198.232184   52.942944  36.373628  16816.901389
450  Female    Middle Class  110.840841   58.122349  20.412186  15921.757539
451  Female            Rich  180.235406   78.990422  26.241729   8841.596690
456  Female            Rich  174.619964   79.549642  22.994649  12215.187011
457  Female            Rich  143.550091   45.388712  35.221450  16908.264982
460  Female            Rich  155.167588    2.963596  26.969665  19197.000268
461  Female    Middle Class  204.619591   53.444895  44.380174  15955.391015
463  Female            Poor  188.178427   33.644124  26.556408  18364.244058
465  Female            Poor  142.781643   83.141827  22.396599  21410.198725
469  Female            Rich  166.311096   24.896342  33.107142  18720.850812
475  Female            Rich  177.219196   82.332669  29.908853  18329.087880
476  Female            Rich  171.989711   54.983507  12.447203  19783.184568
481  Female            Rich  160.100761   98.372355  45.858553  12788.860484
484  Female            Poor  147.170746  100.789389  45.432393  20199.561595
487  Female            Poor  150.379291   88.991787  17.749186  15833.347376
488  Female            Rich  189.925318   60.232040  28.158365  17666.024486
497  Female    Middle Class  130.093762   69.843849  13.326383  16948.866528
499  Female            Poor  153.154213   67.495291  25.662428  22223.983510

[232 rows x 6 columns]

In [17]:
#Cuando deseamos obtener la data de 2 columnas
double_group = data.groupby(["Gender", "Economic Status"])

In [18]:
len(double_group)

6

In [19]:
for names, groups in double_group:
    print(names)
    print(groups)

('Female', 'Middle Class')
     Gender Economic Status      Height      Weight        Age        Income
10   Female    Middle Class   99.326653   35.177586  33.386594  21926.707857
19   Female    Middle Class  163.119879   40.548448  29.989267  20772.916430
21   Female    Middle Class  192.927230   45.182203  50.816121  15472.304732
28   Female    Middle Class  161.033834   89.345970  19.447700  21367.110214
39   Female    Middle Class  129.021196   75.872575  36.757063  11470.084742
50   Female    Middle Class  183.357699   70.987025  14.985370  23436.614682
56   Female    Middle Class  100.694266   63.374240  36.788290  28322.393609
66   Female    Middle Class  169.285250   39.580045  12.013107  23291.291009
80   Female    Middle Class  161.757517  108.717075  34.375814  20576.025997
91   Female    Middle Class  124.102725   84.502284  41.542195  17143.476068
93   Female    Middle Class  131.503042   62.747800  16.256189  26643.870473
105  Female    Middle Class  163.352199   64.666140  62.496177  22256.473303
106  Female    Middle Class  171.122764    4.227599  13.710184  19129.636202
116  Female    Middle Class  177.752292   49.841127  31.045527  20149.998146
118  Female    Middle Class  177.438675   39.965387  29.262483  23429.803565
123  Female    Middle Class  189.551973   88.914028  21.513125  24830.533773
128  Female    Middle Class  202.547403   51.978584  50.786163  24191.115698
145  Female    Middle Class  134.046411   62.811120  24.089247  17168.164604
146  Female    Middle Class  143.013842   21.394311  25.471414  12744.570626
152  Female    Middle Class   98.539654  101.747802  36.614244  10216.840958
153  Female    Middle Class  179.936090   92.372887  41.949814  16200.139684
154  Female    Middle Class  130.357802   65.785528  30.856100  18091.764980
171  Female    Middle Class  138.607655   98.317741  22.683223  17815.650653
184  Female    Middle Class  165.576751   29.032777  19.016661  19319.577469
186  Female    Middle Class  134.913317   75.760599  41.968647  21126.794515
188  Female    Middle Class  135.713325   42.859896  32.972587  25351.405814
191  Female    Middle Class  178.871356   46.361405  30.675486  14711.881556
193  Female    Middle Class  184.373677   73.685694  41.984739  17621.743452
200  Female    Middle Class  167.113434   55.814003  23.127446  13769.995381
204  Female    Middle Class  142.284336   92.695128  20.293560  20051.751679
..      ...             ...         ...         ...        ...           ...
274  Female    Middle Class  176.035197   57.464346  38.632814  21290.292878
291  Female    Middle Class  198.776657   58.810707  10.040180  15558.303205
295  Female    Middle Class  165.833152   82.235972  23.591995  18769.129936
299  Female    Middle Class  182.189917   94.490927  24.553379  18954.769845
302  Female    Middle Class  162.142393  125.931126  40.323894  20405.537880
309  Female    Middle Class  116.203489   24.418396  43.620858  14451.876169
317  Female    Middle Class  152.180123   70.163755  43.602225  18803.887600
321  Female    Middle Class  157.642789   48.821789  40.050375  15306.479169
327  Female    Middle Class  147.847574   70.798454   9.121853  13674.376448
341  Female    Middle Class  156.132519   76.746232  32.917327  19971.847333
343  Female    Middle Class  130.234473   95.932250  30.441264  13672.863927
354  Female    Middle Class  102.049912   16.468686  37.896667  18516.956983
369  Female    Middle Class  149.335635   55.229332  53.336635  19212.912053
370  Female    Middle Class  191.177539   93.266422  27.788739  17885.363353
385  Female    Middle Class  165.538587   71.286405  38.780360  16886.645593
390  Female    Middle Class  157.365208   70.305323  30.171121  19277.821999
391  Female    Middle Class  164.942134   20.661476  56.999229  18556.996978
392  Female    Middle Class  125.052752   35.551944  35.141777  11372.002169
403  Female    Middle Class  131.611016   85.214869  29.136496  18022.577847
405  Female    Middle Class  226.263992   20.485150  26.608910  18054.484754
416  Female    Middle Class  165.602666   12.185388  26.069806  13384.190708
432  Female    Middle Class  170.275384   48.834834  47.378284  16257.070250
434  Female    Middle Class  205.721833   46.089356  28.127938  20573.801101
444  Female    Middle Class  158.088381   66.271985  35.417270  23573.618081
446  Female    Middle Class  137.635809   84.574914  15.826346  15403.117296
447  Female    Middle Class  173.446510   93.515137  43.908351  17833.371375
448  Female    Middle Class  142.314597   51.842130  29.871398  18028.243907
450  Female    Middle Class  110.840841   58.122349  20.412186  15921.757539
461  Female    Middle Class  204.619591   53.444895  44.380174  15955.391015
497  Female    Middle Class  130.093762   69.843849  13.326383  16948.866528

[70 rows x 6 columns]
('Female', 'Poor')
     Gender Economic Status      Height      Weight        Age        Income
0    Female            Poor  145.003227  104.034597  35.487417  22581.327698
5    Female            Poor  169.343943   62.796247  36.268538  27980.733982
29   Female            Poor  107.042841   54.757581  23.665133  18302.670076
34   Female            Poor  174.173457   48.564740  21.621477  12041.856169
35   Female            Poor  181.898603   34.973609  13.394481  21922.464712
42   Female            Poor  169.982715   73.724865  31.504943  15561.156633
46   Female            Poor  135.724487  110.743670  32.651952  19647.050491
48   Female            Poor  106.943685   89.229003  39.220421  16544.362150
54   Female            Poor  178.668405   93.795211  21.025664  20773.193130
61   Female            Poor  153.286507   76.487103  53.117450  16626.242088
68   Female            Poor  176.706476   69.411646  29.465345  18820.786627
86   Female            Poor  139.732637   61.688697  33.359045  25564.560365
87   Female            Poor   93.751837   35.239052  36.180796  19261.621276
97   Female            Poor  213.183948   87.304800  57.903540  24127.640055
102  Female            Poor  120.788377   46.896346  25.174816  16161.907185
103  Female            Poor  139.048914   47.125615  10.908318   8979.358968
117  Female            Poor  165.995717   45.062368  20.054963  11142.026813
124  Female            Poor   78.482727   56.547300  45.035432  20096.803837
132  Female            Poor  163.367567   52.729771  38.298284  20415.524624
135  Female            Poor  179.101591   59.550124  39.750399  16746.762527
137  Female            Poor  129.319680   58.759889  44.638782  17692.598831
143  Female            Poor  161.117055   66.654733  39.018839  23190.687923
155  Female            Poor  179.625298   44.961573  24.568322  18722.229011
158  Female            Poor  159.872818   85.755404  35.917460  18279.617130
161  Female            Poor  132.831937   41.659392  30.408654  19309.875402
164  Female            Poor  158.119218   29.999417  24.005859  17878.708320
177  Female            Poor  183.970770   76.951868  23.404453  15496.692921
178  Female            Poor  206.760901   66.542680   6.516736  19386.580470
182  Female            Poor  156.515682   66.231024  35.393164  12525.343390
187  Female            Poor  170.411558   74.469977  31.583500   9987.654933
..      ...             ...         ...         ...        ...           ...
322  Female            Poor  179.751932   87.248100  20.215513  17266.136777
325  Female            Poor  143.067046   21.349302  36.410986  21488.073515
331  Female            Poor  156.666282   53.631094  38.428923  19746.776539
333  Female            Poor  150.627128  105.638784  48.620488  21651.000389
339  Female            Poor  140.339690   64.056280  31.618235  19490.664206
340  Female            Poor  164.551730  109.908347  34.023720  18202.802240
347  Female            Poor  148.588902   38.001388  30.884748  17548.167552
357  Female            Poor  103.174142   47.780426  52.179911  20261.302477
364  Female            Poor  154.675048   55.261964  16.368001  14485.449934
374  Female            Poor  185.387359  105.326551  26.951044  18791.843692
378  Female            Poor  163.715404   61.599119   9.128209  18996.104869
381  Female            Poor  205.663185   72.183024  54.586828  22310.158332
388  Female            Poor  165.293783   59.134942  32.132166  20037.958801
393  Female            Poor  178.248354   49.646740  30.599195  15783.449987
397  Female            Poor  167.124210   56.370652  43.114139  20133.814777
412  Female            Poor  181.799341   59.455048  26.760501  17025.034966
415  Female            Poor  157.577759   97.665490  28.549766  26448.615457
418  Female            Poor  118.985306   39.938008  23.093400  14838.461691
420  Female            Poor   70.251108   72.772754  34.896448  13955.208307
428  Female            Poor  113.914135   70.050840  42.881517  14039.690366
429  Female            Poor  152.708937   71.239414  35.133849  10307.979864
440  Female            Poor  181.175932   96.729312  24.682871  20988.601022
441  Female            Poor  180.761383   43.873204  28.237756  20218.364184
443  Female            Poor  191.956861   59.530944  24.467168  19823.324263
449  Female            Poor  198.232184   52.942944  36.373628  16816.901389
463  Female            Poor  188.178427   33.644124  26.556408  18364.244058
465  Female            Poor  142.781643   83.141827  22.396599  21410.198725
484  Female            Poor  147.170746  100.789389  45.432393  20199.561595
487  Female            Poor  150.379291   88.991787  17.749186  15833.347376
499  Female            Poor  153.154213   67.495291  25.662428  22223.983510

[77 rows x 6 columns]
('Female', 'Rich')
     Gender Economic Status      Height      Weight        Age        Income
1    Female            Rich  180.604114  117.536593  34.434287  16329.305814
4    Female            Rich  159.208301   69.259598   2.719651  14976.682980
7    Female            Rich  164.237406   78.326334  23.116249  22244.870079
13   Female            Rich  152.293354   93.731695  45.951931  10386.486258
18   Female            Rich  166.928437   50.933272  35.030621  14098.546877
24   Female            Rich  119.678582   58.975352   8.585459  11921.018746
25   Female            Rich  123.159493   27.463171  36.441056  14149.203225
30   Female            Rich  133.286488   61.883725  26.536875  21579.732351
41   Female            Rich  200.861964   39.735186  27.306176  19439.231158
47   Female            Rich  156.172039   62.424292  27.355375  17730.114720
58   Female            Rich  149.749473   61.038524  34.386311  18273.116454
59   Female            Rich  141.634627   49.627084  29.078225  12845.165867
60   Female            Rich  142.299955   82.230375  29.664663  16936.246523
76   Female            Rich  187.151411   36.909128  43.196370  11900.148894
77   Female            Rich  137.934903   96.422243  24.786007  14996.292868
78   Female            Rich  151.965888  176.425741  31.243684  20087.328438
94   Female            Rich  105.203261  115.798481  47.507445  10177.327266
122  Female            Rich  157.444974   66.582659  25.561994  17042.441839
126  Female            Rich  163.309118  151.676403  45.005700  19151.102444
129  Female            Rich  131.892498   47.866469  58.074645  20301.058312
131  Female            Rich  145.192077  106.755611  30.875404  24724.209720
138  Female            Rich  200.597542   43.230402  26.652601  22373.052114
140  Female            Rich  118.865002   58.258079  42.815743  15119.343949
148  Female            Rich  175.906223   73.363340  41.382294  11049.231343
160  Female            Rich  125.163442   70.885464  50.222047  21081.723528
165  Female            Rich  180.158036   94.974176  51.979861  17882.626746
172  Female            Rich  174.922572   66.841521  24.518693  17957.318244
180  Female            Rich  167.130786  106.698154  36.840242  20352.247938
192  Female            Rich  157.359658   32.034926  23.730903  20735.692411
195  Female            Rich  133.844216   30.922264  43.864887  17210.791555
..      ...             ...         ...         ...        ...           ...
318  Female            Rich  138.903338   61.313099  37.160547  15341.577551
319  Female            Rich  169.631921   88.282786  35.079259  16894.239504
326  Female            Rich  207.995200   70.859240  31.223128  19632.365015
330  Female            Rich  148.828327  105.309934  14.787887  16244.786067
337  Female            Rich  198.732811   40.186143  18.836777  23991.994707
338  Female            Rich  137.553178   47.920882  25.448306  14909.873086
349  Female            Rich  131.745670   76.568926  23.539110  14757.006244
351  Female            Rich  176.005975   36.569284  22.051951  13555.430067
353  Female            Rich  170.877204   50.226374  30.676807  15765.700251
358  Female            Rich  139.089232   69.705168  31.417316  16337.834427
360  Female            Rich  124.944093   42.925075  32.107077  14343.268304
368  Female            Rich  192.548651   68.982858  27.451063  12392.926199
371  Female            Rich  198.781079   58.636353  21.315726  19967.209886
372  Female            Rich  149.842784   26.347640  36.495358  22920.521407
394  Female            Rich  108.967079   69.368365  12.205877  19409.713277
398  Female            Rich  176.364016   55.948485  25.020780  17451.150408
400  Female            Rich  127.736107    9.894364  27.178711  23180.869018
417  Female            Rich  185.356428   66.682036  53.964518  19739.564858
430  Female            Rich  204.077483   73.924711  13.181464  18586.719943
435  Female            Rich  201.695130   47.953294  12.164638  21319.987698
437  Female            Rich  141.463187   81.432313  41.165810  22993.657991
451  Female            Rich  180.235406   78.990422  26.241729   8841.596690
456  Female            Rich  174.619964   79.549642  22.994649  12215.187011
457  Female            Rich  143.550091   45.388712  35.221450  16908.264982
460  Female            Rich  155.167588    2.963596  26.969665  19197.000268
469  Female            Rich  166.311096   24.896342  33.107142  18720.850812
475  Female            Rich  177.219196   82.332669  29.908853  18329.087880
476  Female            Rich  171.989711   54.983507  12.447203  19783.184568
481  Female            Rich  160.100761   98.372355  45.858553  12788.860484
488  Female            Rich  189.925318   60.232040  28.158365  17666.024486

[85 rows x 6 columns]
('Male', 'Middle Class')
    Gender Economic Status      Height      Weight        Age        Income
2     Male    Middle Class  147.554611  104.795530  28.570812  17688.434184
11    Male    Middle Class  184.342331   48.014228  23.479574  14414.868112
12    Male    Middle Class  204.313096   81.602032  29.893581  19789.049595
14    Male    Middle Class  140.475187   51.435623  22.462881  17778.968241
15    Male    Middle Class  161.318227  100.840180  32.648121  17058.469525
27    Male    Middle Class  196.679721   46.576822  24.765471  18049.892282
32    Male    Middle Class  165.914861   92.906733  42.620675  13951.012223
36    Male    Middle Class  195.961298   54.031312  29.771976  16400.552096
38    Male    Middle Class  141.754044   67.222383  39.076269  25803.844847
51    Male    Middle Class  157.042143   92.499571  37.315108  19439.465111
53    Male    Middle Class  170.093600   90.078229  36.445166  16491.651714
57    Male    Middle Class  240.427726   36.184287  40.860590  18710.213110
79    Male    Middle Class  155.839077   49.645872  32.681605  17196.825715
81    Male    Middle Class  197.747838   68.921964  39.805233  23425.458734
82    Male    Middle Class  170.586474   52.739308  36.469575  16330.010021
84    Male    Middle Class  175.058465   77.429215  43.929258  19400.685125
95    Male    Middle Class  151.108314   73.095487  16.631516  23982.928810
100   Male    Middle Class  160.839252   71.973418  32.277023  17011.442477
101   Male    Middle Class  151.382461  105.453915  23.515553  24490.094014
107   Male    Middle Class  109.392280   84.347081  24.901979  12924.866930
109   Male    Middle Class  130.769230   95.218897  18.571833  17108.446742
110   Male    Middle Class  144.906545   97.080510  15.242526  16507.870949
112   Male    Middle Class  159.181867   43.357136  22.309237  16818.883417
113   Male    Middle Class  180.414736   99.604211  12.827545  15004.788725
121   Male    Middle Class  140.139739   78.824205  31.518027  22399.646095
127   Male    Middle Class  164.875924   79.422206  44.960776  17475.443984
136   Male    Middle Class  190.021004   26.452340  37.287872  21893.392474
141   Male    Middle Class  145.769996   73.045984  31.380531  14729.753713
147   Male    Middle Class  143.689474   82.679711  36.023763  17315.944507
159   Male    Middle Class  155.891012   77.925002  41.518298  13412.582198
..     ...             ...         ...         ...        ...           ...
324   Male    Middle Class  175.714019   91.181767  33.508832  20745.945323
334   Male    Middle Class  126.502896   64.538414  17.417303  17778.486125
335   Male    Middle Class  156.318147   84.660589   6.109658  14182.383903
355   Male    Middle Class  111.657032   60.175027  27.341174  15918.733652
356   Male    Middle Class  210.718055    5.539667  26.733198  15264.818329
363   Male    Middle Class  159.870146   18.970429  19.297688  17026.967896
366   Male    Middle Class  132.174271   65.446135  24.916450  21077.296177
375   Male    Middle Class  171.100864   53.443405  13.142801  13280.158243
387   Male    Middle Class  178.543586   78.780995  30.602852  18321.628798
396   Male    Middle Class  106.652198   85.712097  30.464046  15271.756584
402   Male    Middle Class  162.307762   64.140097  19.173094  12291.382034
410   Male    Middle Class   74.384994   67.798161  34.095463  15046.420599
414   Male    Middle Class  179.704589   63.048689  32.100964  16584.023989
419   Male    Middle Class  198.232248   41.278366  33.052379  14988.477798
425   Male    Middle Class  195.604477   49.099822  44.460518  19278.412342
427   Male    Middle Class  101.439159   54.922246  33.795401  17684.829913
431   Male    Middle Class  117.793107   53.162862  28.147760  23100.992194
436   Male    Middle Class  180.379480   62.515599  20.056753  21121.660004
439   Male    Middle Class  122.096761   91.764888  25.993180  18867.338215
459   Male    Middle Class  169.983493   80.378619  21.936908  11159.016363
464   Male    Middle Class  182.205639   34.025972  34.727108  21347.384731
466   Male    Middle Class  134.760997   50.674127  24.641276  15648.641449
472   Male    Middle Class  222.407230   43.497227  52.776090  15069.842875
473   Male    Middle Class  144.038160   69.724514  22.190778  15550.606666
480   Male    Middle Class  172.008682  127.911154  33.317179  19265.960131
482   Male    Middle Class  192.663626   80.253718  35.049361  21342.630833
490   Male    Middle Class  142.540566   90.182336  33.021074  20601.926604
491   Male    Middle Class  155.922252   82.555797  59.793334  19042.724663
492   Male    Middle Class  175.056187   39.526115  26.904006  19975.560946
495   Male    Middle Class  110.566745   46.193122  30.404502  14801.618029

[86 rows x 6 columns]
('Male', 'Poor')
    Gender Economic Status      Height      Weight        Age        Income
3     Male            Poor  164.818786   75.742774  52.777811  18062.585082
6     Male            Poor  149.074546   72.288429  18.346359  19159.739373
8     Male            Poor  164.405278   55.250224  19.038873  28492.025708
9     Male            Poor  194.896210   47.093524  43.412001  19241.182225
16    Male            Poor  121.271774   22.903726  38.527925  20562.214179
20    Male            Poor  204.025779   72.348873  25.454164  22060.505237
23    Male            Poor  168.698690   15.276777  21.529697  22121.246982
26    Male            Poor  152.781105   57.876538  21.590702  20747.105554
31    Male            Poor  203.015010   68.669956  20.893979  16636.380866